// Code generated by abstraction-idl from abstraction-download/request.thrift. DO NOT EDIT.

// abstraction.download.request: declarations for index.mjs.

// Expected content identity and size. Empty digest and zero size mean unknown.
// A supplied digest is verified before delivery.
export interface Artifact {
  digest: string;
  size: bigint;
}

// When the executing service may move the bytes. network unmetered opens
// sources only while the platform reports the path unmetered and requires
// abstraction.download/network-cost@1; the attempt waits, holding no lease,
// while the path is metered and resumes with Range. Empty network and any are
// the same. Constraints are evaluated where the bytes move.
export interface Constraints {
  network: Network;
}

export type Network = (typeof Network)[keyof typeof Network];
export declare const Network: Readonly<{ Any: "any"; Unmetered: "unmetered" }>;

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

// Service request payload for recoverable job admission with kind download. The
// provider owns result allocation and all partial files. Request identity,
// required guarantees and cancellation use the job service. This payload
// contains no provider paths. The initial execution profile supports HTTP(S),
// anonymous or with a named credential; unsupported work is sealed as
// definitely not accepted.
export interface Request {
  artifact: Artifact;
  sources: Source[];
  constraints: Constraints | null;
}

// A location interpreted by its named source scheme. Execution providers
// declare which schemes they support. credential, when present, names a
// credential registered with abstraction.credentials/holder@1 in the submitting
// caller's account; it is a name, never a secret. The executing service applies
// it through abstraction.credentials/applier@1 with consumer
// abstraction.download/http-execution@1 to each request it sends to this
// source, including redirects and resumed ranges, and never records the applied
// headers. A request naming a credential requires
// abstraction.download/credentials@1.
export interface Source {
  scheme: string;
  locator: string;
  credential: string;
}

export declare const credentialGuarantees: readonly ["abstraction.download/credentials@1"];

export declare function decode(data: Uint8Array): Request;

export declare function decodeArtifact(data: Uint8Array): Artifact;

export declare function decodeConstraints(data: Uint8Array): Constraints;

export declare function decodeRequest(data: Uint8Array): Request;

export declare function decodeSource(data: Uint8Array): Source;

export declare const downstreamRecoveryGuarantees: readonly ["abstraction.download/recoverable-submission@1"];

export declare function encode(v: Request): Uint8Array;

export declare function encodeArtifact(v: Artifact): Uint8Array;

export declare function encodeConstraints(v: Constraints): Uint8Array;

export declare function encodeRequest(v: Request): Uint8Array;

export declare function encodeSource(v: Source): Uint8Array;

export declare const networkCostGuarantees: readonly ["abstraction.download/network-cost@1"];

export declare function newArtifact(): Artifact;

export declare function newConstraints(): Constraints;

export declare function newRequest(): Request;

export declare function newSource(): Source;

export declare const waitingExtensions: readonly ["abstraction.download/waiting@1"];

export {};
