// Code generated by abstraction-idl from abstraction-download/request.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
function num(out, n) { out.ascii(BigInt(n).toString()); }

function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function writeList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const Network = Object.freeze({
  Any: "any",
  Unmetered: "unmetered",
});

export const downstreamRecoveryGuarantees = ["abstraction.download/recoverable-submission@1"];

export const credentialGuarantees = ["abstraction.download/credentials@1"];

export const networkCostGuarantees = ["abstraction.download/network-cost@1"];

export const waitingExtensions = ["abstraction.download/waiting@1"];

function writeConstraints(out, v, depth) {
    if (v.network !== "") {
    if (typeof v.network !== "string") throw new Refusal("wrong_type",0);
    if (v.network !== "any" && v.network !== "unmetered") { throw new Refusal("bad_enum",0); }
    }
  out.byte(0x7b);
  let first = true;
  if (v.network !== "") {
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "network");
    out.ascii(": ");
    esc(out, v.network);
  }
  if (!first) { out.byte(0x0a); pad(out, depth); }
  out.byte(0x7d);
}

function writeArtifact(out, v, depth) {
  out.byte(0x7b);
  let first = true;
  if (v.digest !== "") {
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "digest");
    out.ascii(": ");
    esc(out, v.digest);
  }
  if (v.size !== 0n) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "size");
    out.ascii(": ");
    num(out, v.size);
  }
  if (!first) { out.byte(0x0a); pad(out, depth); }
  out.byte(0x7d);
}

function writeSource(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "scheme");
  out.ascii(": ");
  esc(out, v.scheme);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "locator");
  out.ascii(": ");
  esc(out, v.locator);
  if (v.credential !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "credential");
    out.ascii(": ");
    esc(out, v.credential);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeRequest(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "artifact");
  out.ascii(": ");
  writeArtifact(out, v.artifact, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "sources");
  out.ascii(": ");
  writeList(out, v.sources, depth + 1, writeSource);
  if (v.constraints !== undefined && v.constraints !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "constraints");
    out.ascii(": ");
    writeConstraints(out, v.constraints, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  writeRequest(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; this.limit = DEPTH_LIMIT; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > this.limit) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function readList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

// When the executing service may move the bytes. network unmetered opens
// sources only while the platform reports the path unmetered and requires
// abstraction.download/network-cost@1; the attempt waits, holding no lease,
// while the path is metered and resumes with Range. Empty network and any are
// the same. Constraints are evaluated where the bytes move.
export function newConstraints() {
  return { network: "" };
}

// Expected content identity and size. Empty digest and zero size mean unknown.
// A supplied digest is verified before delivery.
export function newArtifact() {
  return { digest: "", size: 0n };
}

// A location interpreted by its named source scheme. Execution providers
// declare which schemes they support. credential, when present, names a
// credential registered with abstraction.credentials/holder@1 in the submitting
// caller's account; it is a name, never a secret. The executing service applies
// it through abstraction.credentials/applier@1 with consumer
// abstraction.download/http-execution@1 to each request it sends to this
// source, including redirects and resumed ranges, and never records the applied
// headers. A request naming a credential requires
// abstraction.download/credentials@1.
export function newSource() {
  return { scheme: "", locator: "", credential: "" };
}

// Service request payload for recoverable job admission with kind download. The
// provider owns result allocation and all partial files. Request identity,
// required guarantees and cancellation use the job service. This payload
// contains no provider paths. The initial execution profile supports HTTP(S),
// anonymous or with a named credential; unsupported work is sealed as
// definitely not accepted.
export function newRequest() {
  return { artifact: newArtifact(), sources: [], constraints: null };
}

function readConstraints(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newConstraints();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "network") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.network = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
    if ((seen & 1) !== 0) {
    if (v.network !== "any" && v.network !== "unmetered") { throw r.refuse("bad_enum"); }
    }
  return v;
}

function readArtifact(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newArtifact();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "digest") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.digest = r.string();
      } else if (key === "size") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.size = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

function readSource(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newSource();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "scheme") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.scheme = r.string();
      } else if (key === "locator") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.locator = r.string();
      } else if (key === "credential") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.credential = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readRequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "artifact") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.artifact = readArtifact(r);
      } else if (key === "sources") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.sources = readList(r, readSource);
      } else if (key === "constraints") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.constraints = readConstraints(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = readRequest(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

function refusalRank(word) {
  return refusals.indexOf(word);
}

const _namedRecords = Object.create(null);
_namedRecords["Constraints"] = [["network","string","zero"],];
_namedRecords["Artifact"] = [["digest","string","zero"],["size","i64","zero"],];
_namedRecords["Source"] = [["scheme","string","never"],["locator","string","never"],["credential","string","zero"],];
_namedRecords["Request"] = [["artifact","Artifact","never"],["sources","list<Source>","never"],["constraints","Constraints","absent"],];
function _namedCheck(kind, value, depth = 0, limit = DEPTH_LIMIT) {
  if (depth > limit) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _namedCheck(kind.slice(5,-1), item, depth + 1, limit);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _namedCheck("string",key,depth+1,limit); _namedCheck(kind.slice(11,-1),item,depth+1,limit); }
  } else {
    const fields = _namedRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _namedCheck(type,item,depth+1,limit);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

export function checkConstraints(v, depth = 0, limit = DEPTH_LIMIT) {
  _namedCheck("Constraints", v, depth, Math.min(limit, DEPTH_LIMIT));
}

export function checkArtifact(v, depth = 0, limit = DEPTH_LIMIT) {
  _namedCheck("Artifact", v, depth, Math.min(limit, DEPTH_LIMIT));
}

export function checkSource(v, depth = 0, limit = DEPTH_LIMIT) {
  _namedCheck("Source", v, depth, Math.min(limit, DEPTH_LIMIT));
}

export function checkRequest(v, depth = 0, limit = DEPTH_LIMIT) {
  _namedCheck("Request", v, depth, Math.min(limit, DEPTH_LIMIT));
}

export function decodeConstraintsAt(data, depth, limit) {
  const r = new Reader(data);
  if (depth < 0 || limit < 1) throw r.refuse("depth_exceeded");
  r.depth = depth;
  r.limit = Math.min(limit, DEPTH_LIMIT);
  r.ws();
  const v = readConstraints(r);
  return [v, r.pos];
}

export function encodeConstraintsAt(v, depth) {
  if (depth < 0 || depth >= DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  checkConstraints(v, depth, DEPTH_LIMIT);
  const out = new Out();
  writeConstraints(out, v, depth);
  const bytes = out.bytes();
  decodeConstraintsAt(bytes, depth, DEPTH_LIMIT);
  return bytes;
}

export function encodeConstraints(v) {
  const bytes = encodeConstraintsAt(v, 0);
  const out = new Uint8Array(bytes.length + 1);
  out.set(bytes);
  out[bytes.length] = 0x0a;
  return out;
}

export function decodeConstraints(data) {
  const [v, n] = decodeConstraintsAt(data, 0, DEPTH_LIMIT);
  const r = new Reader(data);
  r.pos = n;
  r.ws();
  if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

export function decodeArtifactAt(data, depth, limit) {
  const r = new Reader(data);
  if (depth < 0 || limit < 1) throw r.refuse("depth_exceeded");
  r.depth = depth;
  r.limit = Math.min(limit, DEPTH_LIMIT);
  r.ws();
  const v = readArtifact(r);
  return [v, r.pos];
}

export function encodeArtifactAt(v, depth) {
  if (depth < 0 || depth >= DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  checkArtifact(v, depth, DEPTH_LIMIT);
  const out = new Out();
  writeArtifact(out, v, depth);
  const bytes = out.bytes();
  decodeArtifactAt(bytes, depth, DEPTH_LIMIT);
  return bytes;
}

export function encodeArtifact(v) {
  const bytes = encodeArtifactAt(v, 0);
  const out = new Uint8Array(bytes.length + 1);
  out.set(bytes);
  out[bytes.length] = 0x0a;
  return out;
}

export function decodeArtifact(data) {
  const [v, n] = decodeArtifactAt(data, 0, DEPTH_LIMIT);
  const r = new Reader(data);
  r.pos = n;
  r.ws();
  if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

export function decodeSourceAt(data, depth, limit) {
  const r = new Reader(data);
  if (depth < 0 || limit < 1) throw r.refuse("depth_exceeded");
  r.depth = depth;
  r.limit = Math.min(limit, DEPTH_LIMIT);
  r.ws();
  const v = readSource(r);
  return [v, r.pos];
}

export function encodeSourceAt(v, depth) {
  if (depth < 0 || depth >= DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  checkSource(v, depth, DEPTH_LIMIT);
  const out = new Out();
  writeSource(out, v, depth);
  const bytes = out.bytes();
  decodeSourceAt(bytes, depth, DEPTH_LIMIT);
  return bytes;
}

export function encodeSource(v) {
  const bytes = encodeSourceAt(v, 0);
  const out = new Uint8Array(bytes.length + 1);
  out.set(bytes);
  out[bytes.length] = 0x0a;
  return out;
}

export function decodeSource(data) {
  const [v, n] = decodeSourceAt(data, 0, DEPTH_LIMIT);
  const r = new Reader(data);
  r.pos = n;
  r.ws();
  if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

export function decodeRequestAt(data, depth, limit) {
  const r = new Reader(data);
  if (depth < 0 || limit < 1) throw r.refuse("depth_exceeded");
  r.depth = depth;
  r.limit = Math.min(limit, DEPTH_LIMIT);
  r.ws();
  const v = readRequest(r);
  return [v, r.pos];
}

export function encodeRequestAt(v, depth) {
  if (depth < 0 || depth >= DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  checkRequest(v, depth, DEPTH_LIMIT);
  const out = new Out();
  writeRequest(out, v, depth);
  const bytes = out.bytes();
  decodeRequestAt(bytes, depth, DEPTH_LIMIT);
  return bytes;
}

export function encodeRequest(v) {
  const bytes = encodeRequestAt(v, 0);
  const out = new Uint8Array(bytes.length + 1);
  out.set(bytes);
  out[bytes.length] = 0x0a;
  return out;
}

export function decodeRequest(data) {
  const [v, n] = decodeRequestAt(data, 0, DEPTH_LIMIT);
  const r = new Reader(data);
  r.pos = n;
  r.ws();
  if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}
