# Code generated by abstraction-idl from abstraction-download/request.thrift. DO NOT EDIT.

"""abstraction.download.request: generated contract types, vocabularies and service clients."""

from ._codec import (
    Artifact,
    CREDENTIAL_GUARANTEES,
    Constraints,
    DOWNSTREAM_RECOVERY_GUARANTEES,
    NETWORK_COST_GUARANTEES,
    Network,
    Refusal,
    Request,
    Source,
    WAITING_EXTENSIONS,
    decode,
    decode_artifact,
    decode_constraints,
    decode_request,
    decode_source,
    encode,
    encode_artifact,
    encode_constraints,
    encode_request,
    encode_source,
)

__all__ = [
    "Artifact",
    "CREDENTIAL_GUARANTEES",
    "Constraints",
    "DOWNSTREAM_RECOVERY_GUARANTEES",
    "NETWORK_COST_GUARANTEES",
    "Network",
    "Refusal",
    "Request",
    "Source",
    "WAITING_EXTENSIONS",
    "decode",
    "decode_artifact",
    "decode_constraints",
    "decode_request",
    "decode_source",
    "encode",
    "encode_artifact",
    "encode_constraints",
    "encode_request",
    "encode_source",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
