# Code generated by abstraction-idl from abstraction-download/request.thrift. DO NOT EDIT.

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def num(out, n):
    out += str(int(n)).encode("ascii")


def pad(out, depth):
    out += b" " * (depth * 2)


def strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        pad(out, depth + 1)
        esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


def raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"

def esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        esc_byte(out, c)
    out += b'"'


def enc_list(out, v, depth, enc):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, x in enumerate(v):
        pad(out, depth + 1)
        enc(out, x, depth + 1)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


DOWNSTREAM_RECOVERY_GUARANTEES = ["abstraction.download/recoverable-submission@1"]


class Artifact:
    def __init__(self, **kw):
        self.digest = kw.get("digest", "")
        self.size = kw.get("size", 0)


class Source:
    def __init__(self, **kw):
        self.scheme = kw.get("scheme", "")
        self.locator = kw.get("locator", "")


class Request:
    def __init__(self, **kw):
        self.artifact = kw.get("artifact", Artifact())
        self.sources = kw.get("sources", [])


def enc_artifact(out, v, depth):
    out += b"{"
    first = True
    if v.digest:
        first = False
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "digest")
        out += b": "
        esc(out, v.digest)
    if v.size != 0:
        if not first:
            out += b","
        first = False
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "size")
        out += b": "
        num(out, v.size)
    if not first:
        out += b"\n"
        pad(out, depth)
    out += b"}"


def enc_source(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "scheme")
    out += b": "
    esc(out, v.scheme)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "locator")
    out += b": "
    esc(out, v.locator)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_request(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "artifact")
    out += b": "
    enc_artifact(out, v.artifact, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "sources")
    out += b": "
    enc_list(out, v.sources, depth + 1, enc_source)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    enc_request(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth", "limit")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0
        self.limit = _DEPTH_LIMIT

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > self.limit:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1


def _decode_list(r, elem):
    if r.at() != _LBRACK:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    out = []
    r.ws()
    if r.at() != _RBRACK:
        while True:
            r.ws()
            out.append(elem(r))
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACK:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return out


def _decode_artifact(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Artifact()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "digest":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.digest = r.string()
            elif key == "size":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.size = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def _decode_source(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Source()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "scheme":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.scheme = r.string()
            elif key == "locator":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.locator = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_request(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Request()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "artifact":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.artifact = _decode_artifact(r)
            elif key == "sources":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.sources = _decode_list(r, _decode_source)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _decode_request(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# REFUSALS is in the order two of them are chosen between.

REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "trailing_bytes"]


def refusal_rank(word):
    return REFUSALS.index(word) if word in REFUSALS else -1

_NAMED_IMPORTED = {}
_NAMED_RECORDS = {
"Artifact":(Artifact,[("digest","string","zero"),("size","i64","zero"),]),
"Source":(Source,[("scheme","string","never"),("locator","string","never"),]),
"Request":(Request,[("artifact","Artifact","never"),("sources","list<Source>","never"),]),
}
def _named_check(kind, value, depth=0,limit=_DEPTH_LIMIT):
    # Python coercions must not silently change typed service arguments.
    if depth >= limit and (kind.startswith(("list<", "map<")) or kind in _NAMED_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "binary":
        valid = type(value) is bytes
    elif kind == "string":
        valid = type(value) is str
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _named_check(kind[5:-1], item, depth + 1, limit)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _named_check("string", key, depth + 1, limit)
                _named_check(kind[11:-1], item, depth + 1, limit)
    elif kind in _NAMED_IMPORTED:
        cls, check = _NAMED_IMPORTED[kind]
        valid = isinstance(value,cls)
        if valid:
            check(value,depth,limit)
    else:
        cls, fields = _NAMED_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _named_check(field_kind, item, depth + 1, limit)
    if not valid:
        raise Refusal("wrong_type", 0)

def check_artifact(v,depth=0,limit=_DEPTH_LIMIT):
    _named_check("Artifact",v,depth,min(limit,_DEPTH_LIMIT))

def check_source(v,depth=0,limit=_DEPTH_LIMIT):
    _named_check("Source",v,depth,min(limit,_DEPTH_LIMIT))

def check_request(v,depth=0,limit=_DEPTH_LIMIT):
    _named_check("Request",v,depth,min(limit,_DEPTH_LIMIT))

def decode_artifact_at(data,depth,limit):
    r = _Reader(bytes(data))
    if depth < 0 or limit < 1:
        raise r.refuse("depth_exceeded")
    r.depth = depth
    r.limit = min(limit,_DEPTH_LIMIT)
    r.ws()
    v = _decode_artifact(r)
    return v,r.pos
def encode_artifact_at(v,depth):
    if depth < 0 or depth >= _DEPTH_LIMIT:
        raise _Reader(b'').refuse("depth_exceeded")
    check_artifact(v,depth,_DEPTH_LIMIT)
    out = bytearray()
    enc_artifact(out,v,depth)
    decode_artifact_at(out,depth,_DEPTH_LIMIT)
    return bytes(out)
def encode_artifact(v):
    return encode_artifact_at(v,0)+"\n".encode()
def decode_artifact(data):
    v,n = decode_artifact_at(data,0,_DEPTH_LIMIT)
    r = _Reader(bytes(data))
    r.pos = n
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return v

def decode_source_at(data,depth,limit):
    r = _Reader(bytes(data))
    if depth < 0 or limit < 1:
        raise r.refuse("depth_exceeded")
    r.depth = depth
    r.limit = min(limit,_DEPTH_LIMIT)
    r.ws()
    v = _decode_source(r)
    return v,r.pos
def encode_source_at(v,depth):
    if depth < 0 or depth >= _DEPTH_LIMIT:
        raise _Reader(b'').refuse("depth_exceeded")
    check_source(v,depth,_DEPTH_LIMIT)
    out = bytearray()
    enc_source(out,v,depth)
    decode_source_at(out,depth,_DEPTH_LIMIT)
    return bytes(out)
def encode_source(v):
    return encode_source_at(v,0)+"\n".encode()
def decode_source(data):
    v,n = decode_source_at(data,0,_DEPTH_LIMIT)
    r = _Reader(bytes(data))
    r.pos = n
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return v

def decode_request_at(data,depth,limit):
    r = _Reader(bytes(data))
    if depth < 0 or limit < 1:
        raise r.refuse("depth_exceeded")
    r.depth = depth
    r.limit = min(limit,_DEPTH_LIMIT)
    r.ws()
    v = _decode_request(r)
    return v,r.pos
def encode_request_at(v,depth):
    if depth < 0 or depth >= _DEPTH_LIMIT:
        raise _Reader(b'').refuse("depth_exceeded")
    check_request(v,depth,_DEPTH_LIMIT)
    out = bytearray()
    enc_request(out,v,depth)
    decode_request_at(out,depth,_DEPTH_LIMIT)
    return bytes(out)
def encode_request(v):
    return encode_request_at(v,0)+"\n".encode()
def decode_request(data):
    v,n = decode_request_at(data,0,_DEPTH_LIMIT)
    r = _Reader(bytes(data))
    r.pos = n
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return v
