// Code generated by abstraction-idl from abstraction-download/request.thrift. DO NOT EDIT.

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

fn enc_list<T>(out: &mut Vec<u8>, v: &[T], depth: i32, enc: fn(&mut Vec<u8>, &T, i32)) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, x) in v.iter().enumerate() {
        pad(out, depth + 1);
        enc(out, x, depth + 1);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

/// The closed vocabulary Network. A reader refuses a name it does not list.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Network {
    Any,
    Unmetered,
}

impl Network {
    /// Every member, in declaration order.
    pub const ALL: [Self; 2] = [Self::Any, Self::Unmetered];

    /// The member's name on the wire.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Any => "any",
            Self::Unmetered => "unmetered",
        }
    }

    /// The member a wire name spells, or `None` for a name this vocabulary refuses.
    pub fn from_wire(name: &str) -> Option<Self> {
        match name {
            "any" => Some(Self::Any),
            "unmetered" => Some(Self::Unmetered),
            _ => None,
        }
    }
}

impl std::fmt::Display for Network {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl PartialEq<str> for Network {
    fn eq(&self, other: &str) -> bool {
        self.as_str() == other
    }
}

impl PartialEq<&str> for Network {
    fn eq(&self, other: &&str) -> bool {
        self.as_str() == *other
    }
}

pub const DOWNSTREAM_RECOVERY_GUARANTEES: [&str; 1] = ["abstraction.download/recoverable-submission@1"];

pub const CREDENTIAL_GUARANTEES: [&str; 1] = ["abstraction.download/credentials@1"];

pub const NETWORK_COST_GUARANTEES: [&str; 1] = ["abstraction.download/network-cost@1"];

pub const WAITING_EXTENSIONS: [&str; 1] = ["abstraction.download/waiting@1"];

/// When the executing service may move the bytes. network unmetered opens
/// sources only while the platform reports the path unmetered and requires
/// abstraction.download/network-cost@1; the attempt waits, holding no lease,
/// while the path is metered and resumes with Range. Empty network and any are
/// the same. Constraints are evaluated where the bytes move.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Constraints {
    pub network: Option<Network>,
}

/// Expected content identity and size. Empty digest and zero size mean unknown.
/// A supplied digest is verified before delivery.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Artifact {
    pub digest: String,
    pub size: i64,
}

/// A location interpreted by its named source scheme. Execution providers
/// declare which schemes they support. credential, when present, names a
/// credential registered with abstraction.credentials/holder@1 in the
/// submitting caller's account; it is a name, never a secret. The executing
/// service applies it through abstraction.credentials/applier@1 with consumer
/// abstraction.download/http-execution@1 to each request it sends to this
/// source, including redirects and resumed ranges, and never records the
/// applied headers. A request naming a credential requires
/// abstraction.download/credentials@1.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Source {
    pub scheme: String,
    pub locator: String,
    pub credential: String,
}

/// Service request payload for recoverable job admission with kind download.
/// The provider owns result allocation and all partial files. Request identity,
/// required guarantees and cancellation use the job service. This payload
/// contains no provider paths. The initial execution profile supports HTTP(S),
/// anonymous or with a named credential; unsupported work is sealed as
/// definitely not accepted.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Request {
    pub artifact: Artifact,
    pub sources: Vec<Source>,
    pub constraints: Option<Constraints>,
}

fn enc_constraints(out: &mut Vec<u8>, v: &Constraints, depth: i32) {
    out.push(b'{');
    let mut first = true;
    if let Some(value) = &v.network {
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "network");
        out.extend_from_slice(b": ");
        esc(out, value.as_str());
    }
    if !first {
        out.push(b'\n');
        pad(out, depth);
    }
    out.push(b'}');
}

fn enc_artifact(out: &mut Vec<u8>, v: &Artifact, depth: i32) {
    out.push(b'{');
    let mut first = true;
    if !v.digest.is_empty() {
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "digest");
        out.extend_from_slice(b": ");
        esc(out, &v.digest);
    }
    if v.size != 0 {
        if !first {
            out.push(b',');
        }
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "size");
        out.extend_from_slice(b": ");
        num(out, v.size);
    }
    if !first {
        out.push(b'\n');
        pad(out, depth);
    }
    out.push(b'}');
}

fn enc_source(out: &mut Vec<u8>, v: &Source, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "scheme");
    out.extend_from_slice(b": ");
    esc(out, &v.scheme);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "locator");
    out.extend_from_slice(b": ");
    esc(out, &v.locator);
    if !v.credential.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "credential");
        out.extend_from_slice(b": ");
        esc(out, &v.credential);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

fn enc_request(out: &mut Vec<u8>, v: &Request, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "artifact");
    out.extend_from_slice(b": ");
    enc_artifact(out, &v.artifact, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "sources");
    out.extend_from_slice(b": ");
    enc_list(out, &v.sources, depth + 1, enc_source);
    if let Some(value) = &v.constraints {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "constraints");
        out.extend_from_slice(b": ");
        enc_constraints(out, value, depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &Request) -> Vec<u8> {
    let mut out = Vec::new();
    enc_request(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
    limit: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > self.limit {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

}

fn decode_list<T>(
    r: &mut Reader,
    elem: fn(&mut Reader) -> Result<T, Refusal>,
) -> Result<Vec<T>, Refusal> {
    if r.at() != b'[' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = Vec::new();
    r.skip_ws();
    if r.at() != b']' {
        loop {
            r.skip_ws();
            out.push(elem(r)?);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b']' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_constraints(r: &mut Reader) -> Result<Constraints, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_network: Option<String> = None;
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "network" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_network = Some(r.string()?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    let field_network = match field_network {
        Some(name) => match Network::from_wire(&name) {
            Some(value) => Some(value),
            None => return r.refuse("bad_enum"),
        },
        None => None,
    };
    Ok(Constraints {
        network: field_network,
    })
}

fn decode_artifact(r: &mut Reader) -> Result<Artifact, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_digest: String = Default::default();
    let mut field_size: i64 = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "digest" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_digest = r.string()?;
                }
                "size" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_size = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(Artifact {
        digest: field_digest,
        size: field_size,
    })
}

fn decode_source(r: &mut Reader) -> Result<Source, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_scheme: String = Default::default();
    let mut field_locator: String = Default::default();
    let mut field_credential: String = Default::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "scheme" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_scheme = r.string()?;
                }
                "locator" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_locator = r.string()?;
                }
                "credential" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_credential = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(Source {
        scheme: field_scheme,
        locator: field_locator,
        credential: field_credential,
    })
}

fn decode_request(r: &mut Reader) -> Result<Request, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut field_artifact: Artifact = Default::default();
    let mut field_sources: Vec<Source> = Default::default();
    let mut field_constraints: Option<Constraints> = None;
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "artifact" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    field_artifact = decode_artifact(r)?;
                }
                "sources" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    field_sources = decode_list(r, decode_source)?;
                }
                "constraints" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    field_constraints = Some(decode_constraints(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(Request {
        artifact: field_artifact,
        sources: field_sources,
        constraints: field_constraints,
    })
}

pub fn decode(data: &[u8]) -> Result<Request, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    let v = decode_request(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn named_encode_constraints(v: &Constraints, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_constraints(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

fn decode_constraints_at(data: &[u8], depth: i32, limit: i32) -> Result<(Constraints, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_constraints(&mut r)?;
    Ok((v, r.pos))
}

fn check_constraints(v: &Constraints, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_constraints(v, depth)?;
    decode_constraints_at(&out, depth, limit).map(|_| ())
}

fn encode_constraints_at(v: &Constraints, depth: i32) -> Result<Vec<u8>, Refusal> {
    if !(0..DEPTH_LIMIT).contains(&depth) {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_constraints(v, depth)?;
    decode_constraints_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_constraints_document(v: &Constraints) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_constraints_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_constraints_document(data: &[u8]) -> Result<Constraints, Refusal> {
    let (v, n) = decode_constraints_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn named_encode_artifact(v: &Artifact, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_artifact(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

fn decode_artifact_at(data: &[u8], depth: i32, limit: i32) -> Result<(Artifact, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_artifact(&mut r)?;
    Ok((v, r.pos))
}

fn check_artifact(v: &Artifact, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_artifact(v, depth)?;
    decode_artifact_at(&out, depth, limit).map(|_| ())
}

fn encode_artifact_at(v: &Artifact, depth: i32) -> Result<Vec<u8>, Refusal> {
    if !(0..DEPTH_LIMIT).contains(&depth) {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_artifact(v, depth)?;
    decode_artifact_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_artifact_document(v: &Artifact) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_artifact_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_artifact_document(data: &[u8]) -> Result<Artifact, Refusal> {
    let (v, n) = decode_artifact_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn named_encode_source(v: &Source, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_source(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

fn decode_source_at(data: &[u8], depth: i32, limit: i32) -> Result<(Source, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_source(&mut r)?;
    Ok((v, r.pos))
}

fn check_source(v: &Source, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_source(v, depth)?;
    decode_source_at(&out, depth, limit).map(|_| ())
}

fn encode_source_at(v: &Source, depth: i32) -> Result<Vec<u8>, Refusal> {
    if !(0..DEPTH_LIMIT).contains(&depth) {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_source(v, depth)?;
    decode_source_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_source_document(v: &Source) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_source_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_source_document(data: &[u8]) -> Result<Source, Refusal> {
    let (v, n) = decode_source_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn named_encode_request(v: &Request, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_request(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

fn decode_request_at(data: &[u8], depth: i32, limit: i32) -> Result<(Request, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_request(&mut r)?;
    Ok((v, r.pos))
}

fn check_request(v: &Request, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_request(v, depth)?;
    decode_request_at(&out, depth, limit).map(|_| ())
}

fn encode_request_at(v: &Request, depth: i32) -> Result<Vec<u8>, Refusal> {
    if !(0..DEPTH_LIMIT).contains(&depth) {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_request(v, depth)?;
    decode_request_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_request_document(v: &Request) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_request_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_request_document(data: &[u8]) -> Result<Request, Refusal> {
    let (v, n) = decode_request_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

/// Items generated crates that include this one, and conformance drivers,
/// reach. Nothing here is API; it may change in any release.
pub mod internal {
    pub fn decode_constraints_at(data: &[u8], depth: i32, limit: i32) -> Result<(super::Constraints, usize), super::Refusal> {
        super::decode_constraints_at(data, depth, limit)
    }

    pub fn check_constraints(v: &super::Constraints, depth: i32, limit: i32) -> Result<(), super::Refusal> {
        super::check_constraints(v, depth, limit)
    }

    pub fn encode_constraints_at(v: &super::Constraints, depth: i32) -> Result<Vec<u8>, super::Refusal> {
        super::encode_constraints_at(v, depth)
    }

    pub fn decode_artifact_at(data: &[u8], depth: i32, limit: i32) -> Result<(super::Artifact, usize), super::Refusal> {
        super::decode_artifact_at(data, depth, limit)
    }

    pub fn check_artifact(v: &super::Artifact, depth: i32, limit: i32) -> Result<(), super::Refusal> {
        super::check_artifact(v, depth, limit)
    }

    pub fn encode_artifact_at(v: &super::Artifact, depth: i32) -> Result<Vec<u8>, super::Refusal> {
        super::encode_artifact_at(v, depth)
    }

    pub fn decode_source_at(data: &[u8], depth: i32, limit: i32) -> Result<(super::Source, usize), super::Refusal> {
        super::decode_source_at(data, depth, limit)
    }

    pub fn check_source(v: &super::Source, depth: i32, limit: i32) -> Result<(), super::Refusal> {
        super::check_source(v, depth, limit)
    }

    pub fn encode_source_at(v: &super::Source, depth: i32) -> Result<Vec<u8>, super::Refusal> {
        super::encode_source_at(v, depth)
    }

    pub fn decode_request_at(data: &[u8], depth: i32, limit: i32) -> Result<(super::Request, usize), super::Refusal> {
        super::decode_request_at(data, depth, limit)
    }

    pub fn check_request(v: &super::Request, depth: i32, limit: i32) -> Result<(), super::Refusal> {
        super::check_request(v, depth, limit)
    }

    pub fn encode_request_at(v: &super::Request, depth: i32) -> Result<Vec<u8>, super::Refusal> {
        super::encode_request_at(v, depth)
    }
}
