// Code generated by abstraction-idl from abstraction-download/request.thrift. DO NOT EDIT.

#![allow(dead_code)]

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

pub fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

pub fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

pub fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

pub fn raw(out: &mut Vec<u8>, b: &[u8], depth: i32) {
    let mut depth = depth;
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if ws(c) {
            i += 1;
        } else if c == b'"' {
            let mut j = i + 1;
            while j < b.len() {
                if b[j] == b'\\' {
                    j += 2;
                    continue;
                }
                if b[j] == b'"' {
                    j += 1;
                    break;
                }
                j += 1;
            }
            out.extend_from_slice(&b[i..j]);
            i = j;
        } else if c == b'{' || c == b'[' {
            out.push(c);
            i += 1;
            let mut j = i;
            while j < b.len() && ws(b[j]) {
                j += 1;
            }
            if j < b.len() && (b[j] == b'}' || b[j] == b']') {
                out.push(b[j]);
                i = j + 1;
            } else {
                depth += 1;
                out.push(b'\n');
                pad(out, depth);
            }
        } else if c == b'}' || c == b']' {
            depth -= 1;
            out.push(b'\n');
            pad(out, depth);
            out.push(c);
            i += 1;
        } else if c == b',' {
            out.extend_from_slice(b",\n");
            pad(out, depth);
            i += 1;
        } else if c == b':' {
            out.extend_from_slice(b": ");
            i += 1;
        } else {
            out.push(c);
            i += 1;
        }
    }
}

// A BTreeMap<String, _> walks its keys in String's Ord, which compares the
// UTF-8 bytes — the order the definition declares. Nothing sorts here.
pub fn rawmap(out: &mut Vec<u8>, m: &BTreeMap<String, Raw>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        raw(out, v, depth + 1);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

pub fn enc_list<T>(out: &mut Vec<u8>, v: &[T], depth: i32, enc: fn(&mut Vec<u8>, &T, i32)) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, x) in v.iter().enumerate() {
        pad(out, depth + 1);
        enc(out, x, depth + 1);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

pub const DOWNSTREAM_RECOVERY_GUARANTEES: [&str; 1] = ["abstraction.download/recoverable-submission@1"];

#[derive(Default)]
pub struct Artifact {
    pub digest: String,
    pub size: i64,
}

#[derive(Default)]
pub struct Source {
    pub scheme: String,
    pub locator: String,
}

#[derive(Default)]
pub struct Request {
    pub artifact: Artifact,
    pub sources: Vec<Source>,
}

pub fn enc_artifact(out: &mut Vec<u8>, v: &Artifact, depth: i32) {
    out.push(b'{');
    let mut first = true;
    if !v.digest.is_empty() {
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "digest");
        out.extend_from_slice(b": ");
        esc(out, &v.digest);
    }
    if v.size != 0 {
        if !first {
            out.push(b',');
        }
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "size");
        out.extend_from_slice(b": ");
        num(out, v.size);
    }
    if !first {
        out.push(b'\n');
        pad(out, depth);
    }
    out.push(b'}');
}

pub fn enc_source(out: &mut Vec<u8>, v: &Source, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "scheme");
    out.extend_from_slice(b": ");
    esc(out, &v.scheme);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "locator");
    out.extend_from_slice(b": ");
    esc(out, &v.locator);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_request(out: &mut Vec<u8>, v: &Request, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "artifact");
    out.extend_from_slice(b": ");
    enc_artifact(out, &v.artifact, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "sources");
    out.extend_from_slice(b": ");
    enc_list(out, &v.sources, depth + 1, enc_source);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &Request) -> Vec<u8> {
    let mut out = Vec::new();
    enc_request(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
    limit: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > self.limit {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_map(&mut self) -> Result<BTreeMap<String, Raw>, Refusal> {
        if self.at() != b'{' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.at() != b'}' {
            loop {
                self.skip_ws();
                if self.at() != b'"' {
                    return self.refuse("malformed");
                }
                let k = self.string()?;
                if out.contains_key(&k) {
                    return self.refuse("duplicate_key");
                }
                self.skip_ws();
                if self.at() != b':' {
                    return self.refuse("malformed");
                }
                self.pos += 1;
                self.skip_ws();
                let v = self.raw_value()?;
                out.insert(k, v);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b'}' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        let mut seen: BTreeMap<String, bool> = BTreeMap::new();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    let k = self.string()?;
                    if seen.insert(k, true).is_some() {
                        return self.refuse("duplicate_key");
                    }
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn decode_list<T>(
    r: &mut Reader,
    elem: fn(&mut Reader) -> Result<T, Refusal>,
) -> Result<Vec<T>, Refusal> {
    if r.at() != b'[' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = Vec::new();
    r.skip_ws();
    if r.at() != b']' {
        loop {
            r.skip_ws();
            out.push(elem(r)?);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b']' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_artifact(r: &mut Reader) -> Result<Artifact, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Artifact::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "digest" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.digest = r.string()?;
                }
                "size" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.size = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(v)
}

fn decode_source(r: &mut Reader) -> Result<Source, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Source::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "scheme" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.scheme = r.string()?;
                }
                "locator" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.locator = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_request(r: &mut Reader) -> Result<Request, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Request::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "artifact" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.artifact = decode_artifact(r)?;
                }
                "sources" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.sources = decode_list(r, decode_source)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

pub fn decode(data: &[u8]) -> Result<Request, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    let v = decode_request(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

// REFUSALS is in the order two of them are chosen between.
pub const REFUSALS: [&str; 10] = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "trailing_bytes"];

pub fn refusal_rank(word: &str) -> i32 {
    match REFUSALS.iter().position(|w| *w == word) {
        Some(i) => i as i32,
        None => -1,
    }
}

fn named_encode_artifact(v: &Artifact, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_artifact(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

pub fn decode_artifact_at(data: &[u8], depth: i32, limit: i32) -> Result<(Artifact, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_artifact(&mut r)?;
    Ok((v, r.pos))
}

pub fn check_artifact(v: &Artifact, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_artifact(v, depth)?;
    decode_artifact_at(&out, depth, limit).map(|_| ())
}

pub fn encode_artifact_at(v: &Artifact, depth: i32) -> Result<Vec<u8>, Refusal> {
    if depth < 0 || depth >= DEPTH_LIMIT {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_artifact(v, depth)?;
    decode_artifact_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_artifact_document(v: &Artifact) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_artifact_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_artifact_document(data: &[u8]) -> Result<Artifact, Refusal> {
    let (v, n) = decode_artifact_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn named_encode_source(v: &Source, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_source(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

pub fn decode_source_at(data: &[u8], depth: i32, limit: i32) -> Result<(Source, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_source(&mut r)?;
    Ok((v, r.pos))
}

pub fn check_source(v: &Source, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_source(v, depth)?;
    decode_source_at(&out, depth, limit).map(|_| ())
}

pub fn encode_source_at(v: &Source, depth: i32) -> Result<Vec<u8>, Refusal> {
    if depth < 0 || depth >= DEPTH_LIMIT {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_source(v, depth)?;
    decode_source_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_source_document(v: &Source) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_source_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_source_document(data: &[u8]) -> Result<Source, Refusal> {
    let (v, n) = decode_source_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

fn named_encode_request(v: &Request, depth: i32) -> Result<Vec<u8>, Refusal> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let mut out = Vec::new();
        enc_request(&mut out, v, depth);
        out
    })) {
        Ok(out) => Ok(out),
        Err(p) => match p.downcast::<Refusal>() {
            Ok(e) => Err(*e),
            Err(p) => std::panic::resume_unwind(p),
        },
    }
}

pub fn decode_request_at(data: &[u8], depth: i32, limit: i32) -> Result<(Request, usize), Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth, limit: if limit < DEPTH_LIMIT { limit } else { DEPTH_LIMIT } };
    if depth < 0 || limit < 1 {
        return r.refuse("depth_exceeded");
    }
    r.skip_ws();
    let v = decode_request(&mut r)?;
    Ok((v, r.pos))
}

pub fn check_request(v: &Request, depth: i32, limit: i32) -> Result<(), Refusal> {
    if depth < 0 || limit < 1 {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_request(v, depth)?;
    decode_request_at(&out, depth, limit).map(|_| ())
}

pub fn encode_request_at(v: &Request, depth: i32) -> Result<Vec<u8>, Refusal> {
    if depth < 0 || depth >= DEPTH_LIMIT {
        return Err(Refusal { word: "depth_exceeded", offset: 0 });
    }
    let out = named_encode_request(v, depth)?;
    decode_request_at(&out, depth, DEPTH_LIMIT)?;
    Ok(out)
}

pub fn encode_request_document(v: &Request) -> Result<Vec<u8>, Refusal> {
    let mut out = encode_request_at(v, 0)?;
    out.push(b'\n');
    Ok(out)
}

pub fn decode_request_document(data: &[u8]) -> Result<Request, Refusal> {
    let (v, n) = decode_request_at(data, 0, DEPTH_LIMIT)?;
    let mut r = Reader { buf: data, pos: n, depth: 0, limit: DEPTH_LIMIT };
    r.skip_ws();
    if r.pos != data.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}
